//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DucPhamStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatHang
    {
        public string MaMatHang { get; set; }
        public string TenMatHang { get; set; }
        public string MaLoai { get; set; }
        public string MaHang { get; set; }
        public long Gia { get; set; }
        public long SoLuong { get; set; }
        public string Anh { get; set; }
        public string MoTa { get; set; }
        public bool Active { get; set; }
    
        public virtual Hang Hang { get; set; }
        public virtual Loai Loai { get; set; }
    }
}
